# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.0.1
    hooks:
      # проверяет наличие переноса строки в конце всех текстовых файлов
      - id: end-of-file-fixer
      # предупреждает о добавлении больших файлов в Git
      - id: check-added-large-files
      # предупреждает о сохранении файлов с UTF-8 BOM
      - id: check-byte-order-marker
      # предотвращает сохранение приватных ключей
      - id: detect-private-key
      # проверяет, что файлы, которые мы собираемся сохранять, как минимум валидный Python
      - id: check-ast
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: 'https://github.com/psf/black'
    rev: 21.8b0
    hooks:
      - id: black
        args: [--line-length=79]
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.9.3
    hooks:
      - id: isort
  # - repo: 'https://github.com/FalconSocial/pre-commit-mirrors-pep257'
  #   rev: v0.3.3
  #   hooks:
  #     - id: pep257
